export const data = [
  {
    id: 1,
    name: "John Doe",
    gender: "Male",
    salary: 55000,
  },
  {
    id: 2,
    name: "Jane Smith",
    gender: "Female",
    salary: 63000,
  },
  {
    id: 3,
    name: "Alice Johnson",
    gender: "Female",
    salary: 72000,
  },
  {
    id: 4,
    name: "Robert Brown",
    gender: "Male",
    salary: 48000,
  },
  {
    id: 5,
    name: "Emily Davis",
    gender: "Female",
    salary: 51000,
  },
  {
    id: 6,
    name: "Michael Wilson",
    gender: "Male",
    salary: 59000,
  },
  {
    id: 7,
    name: "Sophia Moore",
    gender: "Female",
    salary: 67000,
  },
  {
    id: 8,
    name: "Daniel Taylor",
    gender: "Male",
    salary: 75000,
  },
  {
    id: 9,
    name: "Olivia Anderson",
    gender: "Female",
    salary: 56000,
  },
  {
    id: 10,
    name: "William Thomas",
    gender: "Male",
    salary: 81000,
  },
  {
    id: 11,
    name: "Emma Harris",
    gender: "Female",
    salary: 59000,
  },
  {
    id: 12,
    name: "James Clark",
    gender: "Male",
    salary: 62000,
  },
  {
    id: 13,
    name: "Amelia Lewis",
    gender: "Female",
    salary: 68000,
  },
  {
    id: 14,
    name: "Mason Walker",
    gender: "Male",
    salary: 70000,
  },
  {
    id: 15,
    name: "Isabella Lee",
    gender: "Female",
    salary: 55000,
  },
  {
    id: 16,
    name: "Lucas Hall",
    gender: "Male",
    salary: 62000,
  },
  {
    id: 17,
    name: "Charlotte Allen",
    gender: "Female",
    salary: 69000,
  },
  {
    id: 18,
    name: "Liam Scott",
    gender: "Male",
    salary: 58000,
  },
  {
    id: 19,
    name: "Ava Young",
    gender: "Female",
    salary: 64000,
  },
  {
    id: 20,
    name: "Henry King",
    gender: "Male",
    salary: 71000,
  },
  {
    id: 21,
    name: "Evelyn Wright",
    gender: "Female",
    salary: 67000,
  },
  {
    id: 22,
    name: "Alexander Baker",
    gender: "Male",
    salary: 50000,
  },
  {
    id: 23,
    name: "Mia Green",
    gender: "Female",
    salary: 72000,
  },
  {
    id: 24,
    name: "Benjamin Adams",
    gender: "Male",
    salary: 75000,
  },
  {
    id: 25,
    name: "Harper Nelson",
    gender: "Female",
    salary: 58000,
  },
  {
    id: 26,
    name: "David Carter",
    gender: "Male",
    salary: 69000,
  },
  {
    id: 27,
    name: "Ella Mitchell",
    gender: "Female",
    salary: 62000,
  },
  {
    id: 28,
    name: "Joseph Perez",
    gender: "Male",
    salary: 63000,
  },
  {
    id: 29,
    name: "Grace Roberts",
    gender: "Female",
    salary: 66000,
  },
  {
    id: 30,
    name: "Samuel Turner",
    gender: "Male",
    salary: 71000,
  },
  {
    id: 31,
    name: "Victoria Phillips",
    gender: "Female",
    salary: 58000,
  },
  {
    id: 32,
    name: "Matthew Campbell",
    gender: "Male",
    salary: 67000,
  },
  {
    id: 33,
    name: "Scarlett Parker",
    gender: "Female",
    salary: 72000,
  },
  {
    id: 34,
    name: "Jack Evans",
    gender: "Male",
    salary: 54000,
  },
  {
    id: 35,
    name: "Madison Edwards",
    gender: "Female",
    salary: 75000,
  },
  {
    id: 36,
    name: "Oliver Collins",
    gender: "Male",
    salary: 60000,
  },
  {
    id: 37,
    name: "Lily Stewart",
    gender: "Female",
    salary: 62000,
  },
  {
    id: 38,
    name: "Ryan Morris",
    gender: "Male",
    salary: 71000,
  },
  {
    id: 39,
    name: "Zoey Bell",
    gender: "Female",
    salary: 64000,
  },
  {
    id: 40,
    name: "Isaac Rogers",
    gender: "Male",
    salary: 56000,
  },
  {
    id: 41,
    name: "Hannah Bennett",
    gender: "Female",
    salary: 58000,
  },
  {
    id: 42,
    name: "Nathan Cooper",
    gender: "Male",
    salary: 66000,
  },
  {
    id: 43,
    name: "Avery Bailey",
    gender: "Female",
    salary: 71000,
  },
  {
    id: 44,
    name: "Ethan Reed",
    gender: "Male",
    salary: 67000,
  },
  {
    id: 45,
    name: "Addison Howard",
    gender: "Female",
    salary: 59000,
  },
  {
    id: 46,
    name: "Logan Ramirez",
    gender: "Male",
    salary: 75000,
  },
  {
    id: 47,
    name: "Mila Peterson",
    gender: "Female",
    salary: 54000,
  },
  {
    id: 48,
    name: "Gabriel Wood",
    gender: "Male",
    salary: 69000,
  },
  {
    id: 49,
    name: "Aria Gonzalez",
    gender: "Female",
    salary: 62000,
  },
  {
    id: 50,
    name: "Caleb Fisher",
    gender: "Male",
    salary: 56000,
  },
  {
    id: 51,
    name: "Scarlett Hill",
    gender: "Female",
    salary: 63000,
  },
  {
    id: 52,
    name: "Jonathan Martin",
    gender: "Male",
    salary: 72000,
  },
  {
    id: 53,
    name: "Sophie Bryant",
    gender: "Female",
    salary: 61000,
  },
  {
    id: 54,
    name: "Christopher Alexander",
    gender: "Male",
    salary: 60000,
  },
  {
    id: 55,
    name: "Riley Perry",
    gender: "Female",
    salary: 75000,
  },
  {
    id: 56,
    name: "Joshua Murphy",
    gender: "Male",
    salary: 71000,
  },
  {
    id: 57,
    name: "Isabella Powell",
    gender: "Female",
    salary: 54000,
  },
  {
    id: 58,
    name: "Dylan Long",
    gender: "Male",
    salary: 68000,
  },
];
